### ISSUE TITLE
Why aren't moveresizes effective immediately?

### ISSUE THREAD

**Issue by Nenuphar** [BurntSushi/xpybutil#6]
Hey,
I'm writing a small tiling utility for Openbox, and it works. My problem is that I use the window.moveresize() function, and it basically doesn't do anything at the time it's called.
I noticed that the changes occur only when I use a get_geometry() function later, as if it forced windows positions to update.
For now, I put this line at the end of my script:
print (window.get_geometry(client_list[0]))
but it seems very hacky and I wonder if I'm doing something wrong or if it's a xpybutil bug of some kind.
Cheers,
Ant.

**Comment by BurntSushi** [comment]
It would help if you could some minimal code that shows your problem, otherwise it's very difficult for others to help debug your problem.

In the mean time, I'd suggest that you read the "EWMH and ICCCM" section of the README. My suspicion is that you probably want to use the `checked` version of moveresize.
